# Generated by Django 2.2.19 on 2022-08-12 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='abc', max_length=20, verbose_name='名称')),
                ('sex', models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('p', models.SmallIntegerField(blank=True, null=True, verbose_name='P')),
                ('one', models.SmallIntegerField(blank=True, null=True, verbose_name='One')),
            ],
            options={
                'verbose_name': '用户',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='名称')),
                ('p', models.SmallIntegerField(db_index=True, default=0, verbose_name='机组')),
                ('status', models.SmallIntegerField(choices=[(1, '在用'), (2, '备用'), (3, '故障'), (4, '下线'), (6, '其它')], db_index=True, default=1, verbose_name='设备状态')),
                ('asset_type', models.SmallIntegerField(choices=[(1, '物理机'), (2, '虚拟机'), (3, '容器'), (4, '交换机'), (6, '其它')], db_index=True, default=2, verbose_name='设备类型')),
                ('remark', models.CharField(db_index=True, default='未填写', max_length=50, verbose_name='说明')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改')),
                ('enable', models.BooleanField(default=True, verbose_name='启用')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '主机',
                'ordering': ['p', 'name'],
            },
        ),
    ]
