# Generated by Django 2.2.19 on 2021-10-20 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='bbb', max_length=30, verbose_name='名称')),
            ],
            options={
                'verbose_name': 'BB',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='mmm', max_length=30, verbose_name='名称')),
            ],
            options={
                'verbose_name': 'M',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ooo', max_length=30, verbose_name='名称')),
                ('b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a.B', verbose_name='B')),
            ],
            options={
                'verbose_name': 'OO',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ppp', max_length=30, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a.B', verbose_name='B')),
            ],
            options={
                'verbose_name': '类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='T',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ttt', max_length=30, verbose_name='名称')),
                ('one', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a.One', verbose_name='One')),
                ('p', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a.P', verbose_name='P')),
            ],
            options={
                'verbose_name': 'T',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='M2T',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.M', verbose_name='M')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.T', verbose_name='T')),
            ],
            options={
                'verbose_name': 'M2T',
            },
        ),
        migrations.AddField(
            model_name='m',
            name='one',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a.One', verbose_name='One'),
        ),
        migrations.AddField(
            model_name='m',
            name='p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a.P', verbose_name='P'),
        ),
        migrations.AddField(
            model_name='m',
            name='t',
            field=models.ManyToManyField(blank=True, to='a.T', verbose_name='T'),
        ),
    ]
