# Generated by Django 2.2.19 on 2022-06-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0001_initial'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='one',
        #     options={'ordering': ['name'], 'verbose_name': 'o2o表'},
        # ),
        # migrations.AlterModelOptions(
        #     name='p',
        #     options={'ordering': ['name'], 'verbose_name': '外键表'},
        # ),
        # migrations.RemoveField(
        #     model_name='m',
        #     name='one',
        # ),
        # migrations.RemoveField(
        #     model_name='m',
        #     name='p',
        # ),
        # migrations.AddField(
        #     model_name='m',
        #     name='one_id',
        #     field=models.SmallIntegerField(blank=True, null=True, verbose_name='One++'),
        # ),
        # migrations.AddField(
        #     model_name='m',
        #     name='p_id',
        #     field=models.SmallIntegerField(blank=True, null=True, verbose_name='One++'),
        # ),
        # migrations.AlterField(
        #     model_name='t',
        #     name='one',
        #     field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t', to='a.One', verbose_name='One'),
        # ),
        # migrations.AlterField(
        #     model_name='t',
        #     name='p',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t', to='a.P', verbose_name='P'),
        # ),
    ]
