# Generated by Django 2.2.19 on 2022-06-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_auto_20220628_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2',
            fields=[
                ('p', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ext', serialize=False, to='a.P')),
                ('name2', models.CharField(default='ppp2', max_length=30, verbose_name='名称2')),
            ],
            options={
                'verbose_name': '外键表2',
                'ordering': ['name2'],
            },
            bases=('a.p',),
        ),
        migrations.CreateModel(
            name='P3',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ext3', serialize=False, to='a.P')),
                ('name3', models.CharField(default='ppp3', max_length=30, verbose_name='名称3')),
            ],
            options={
                'verbose_name': '外键表3',
                'ordering': ['name3'],
            },
        ),
    ]
