# Generated by Django 2.2.19 on 2021-11-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='demoooo', max_length=30, verbose_name='名称')),
                ('p_id', models.SmallIntegerField(blank=True, null=True, verbose_name='P')),
                ('one_id', models.SmallIntegerField(blank=True, null=True, verbose_name='One')),
            ],
            options={
                'verbose_name': 'Demo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Middle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_id', models.SmallIntegerField(verbose_name='Demo')),
                ('t_id', models.SmallIntegerField(verbose_name='T')),
            ],
            options={
                'verbose_name': '虚拟关联m2m中间表',
                'unique_together': {('demo_id', 't_id')},
            },
        ),
    ]
